import { existsSync } from "node:fs";
import { execFile as execFileCallback } from "node:child_process";
import { homedir, platform } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";

/*
  Will install the root certificate authority certificate generated by the
  generate-ca.ts script into the system trust store.

  Currently only works for MacOS.
 */

const execFile = promisify(execFileCallback);

const buildDirPath = resolve(process.cwd(), "build-ca");
const rootCaCertPath = join(
  buildDirPath,
  "certificate-authority",
  "ca-root.crt",
);
const loginKeychainPath = join(
  homedir(),
  "Library",
  "Keychains",
  "login.keychain-db",
);

async function main() {
  if (platform() !== "darwin") {
    throw new Error(
      `install-root-ca-cert.ts only supports macOS (darwin). Current platform is ${platform()}.`,
    );
  }

  if (!existsSync(rootCaCertPath)) {
    throw new Error(
      `Root CA certificate not found at ${rootCaCertPath}. Run generate-ca.ts first to create build-ca output.`,
    );
  }

  console.log(
    `Installing root CA certificate into login keychain: ${loginKeychainPath}`,
  );
  const { stdout, stderr } = await execFile("security", [
    "add-trusted-cert",
    // -r trustRoot marks the cert as a trusted root certificate.
    "-r",
    "trustRoot",
    // -k chooses the keychain file where the cert will be installed.
    "-k",
    loginKeychainPath,
    // Final positional argument is the certificate file to import.
    rootCaCertPath,
  ]);

  if (stdout) {
    console.log(stdout);
  }
  if (stderr) {
    console.error(stderr);
  }

  console.log("Root CA certificate installed successfully.");
}

main().catch(handleFatalError);

function handleFatalError(error: unknown) {
  console.error(error);
  process.exitCode = 1;
}
