import { existsSync } from "node:fs";
import { execFile as execFileCallback } from "node:child_process";
import { platform } from "node:os";
import { resolve } from "node:path";
import { promisify } from "node:util";
import {
  getDefaultBuildCaPath,
  getLoginKeychainPath,
  getRootCaCertPath,
} from "./util/paths.ts";

/*
  Will install the root certificate authority certificate generated by the
  generate-ca.ts script into the system trust store.

  Currently only works for MacOS.
 */

const execFile = promisify(execFileCallback);

const defaultRootCaCertPath = getRootCaCertPath(getDefaultBuildCaPath());
const loginKeychainPath = getLoginKeychainPath();

if (import.meta.main) {
  installCa().catch(handleFatalError);
}

export async function installCa(certificatePath = defaultRootCaCertPath) {
  const resolvedCertificatePath = resolve(certificatePath);

  if (platform() !== "darwin") {
    throw new Error(
      `install-ca.ts only supports macOS (darwin). Current platform is ${platform()}.`,
    );
  }

  if (!existsSync(resolvedCertificatePath)) {
    throw new Error(
      `Root CA certificate not found at ${resolvedCertificatePath}. Run generate-ca.ts first to create build-ca output.`,
    );
  }

  console.log(
    `Installing root CA certificate into login keychain: ${loginKeychainPath}`,
  );
  const { stdout, stderr } = await execFile("security", [
    "add-trusted-cert",
    // -r trustRoot marks the cert as a trusted root certificate.
    "-r",
    "trustRoot",
    // -k chooses the keychain file where the cert will be installed.
    "-k",
    loginKeychainPath,
    // Final positional argument is the certificate file to import.
    resolvedCertificatePath,
  ]);

  if (stdout) {
    console.log(stdout);
  }
  if (stderr) {
    console.error(stderr);
  }

  console.log("Root CA certificate installed successfully.");
}

function handleFatalError(error: unknown) {
  console.error(error);
  process.exitCode = 1;
}
