import { existsSync } from "node:fs";
import { execFile as execFileCallback } from "node:child_process";
import { homedir, platform } from "node:os";
import { join, resolve } from "node:path";
import { promisify } from "node:util";

/*
  Will remove the root certificate authority certificate generated by the
  generate-ca.ts script from the system trust store.

  Currently only works for MacOS.
 */

const execFile = promisify(execFileCallback);

const buildDirPath = resolve(process.cwd(), "build-ca");
const defaultRootCaCertPath = join(buildDirPath, "ca-root.crt");
const loginKeychainPath = join(
  homedir(),
  "Library",
  "Keychains",
  "login.keychain-db",
);

if (import.meta.main) {
  uninstallCa().catch(handleFatalError);
}

export async function uninstallCa(certificatePath = defaultRootCaCertPath) {
  const resolvedCertificatePath = resolve(certificatePath);

  if (platform() !== "darwin") {
    throw new Error(
      `uninstall-ca.ts only supports macOS (darwin). Current platform is ${platform()}.`,
    );
  }

  if (!existsSync(resolvedCertificatePath)) {
    throw new Error(
      `Root CA certificate not found at ${resolvedCertificatePath}. Run generate-ca.ts first to create build-ca output.`,
    );
  }

  console.log(
    `Deleting root CA certificate from login keychain: ${loginKeychainPath}`,
  );
  const certificateFingerprint = await getCertificateFingerprint(
    resolvedCertificatePath,
  );
  await execFile("security", [
    "delete-certificate",
    "-Z",
    certificateFingerprint,
    "-t",
    loginKeychainPath,
  ]);

  console.log("Root CA certificate removed successfully.");
}
async function getCertificateFingerprint(certificatePath: string) {
  const { stdout } = await execFile("openssl", [
    "x509",
    "-in",
    certificatePath,
    "-noout",
    "-fingerprint",
    "-sha256",
  ]);

  const fingerprint = stdout
    .trim()
    .split("=")
    .at(1)
    ?.replaceAll(":", "")
    .trim();

  if (fingerprint) {
    return fingerprint;
  }

  throw new Error(
    `Could not determine SHA-256 fingerprint for certificate at ${certificatePath}.`,
  );
}

function handleFatalError(error: unknown) {
  console.error(error);
  process.exitCode = 1;
}
